branches:
  except:
    - gh-pages

language: cpp

os:
  - linux

compiler:
  - clang
#  - gcc

env:
  global:
    - NUPIC=$TRAVIS_BUILD_DIR
    - PATH=$TRAVIS_BUILD_DIR/python/bin:$PATH
  matrix:
#    - PY_VER=2.7
    - PY_VER=2.6

matrix:
  # This excludes OSX builds from the build matrix for gcc and Python 2.6
  exclude:
    - os: osx
      env: PY_VER=2.6
    - os: osx
      compiler: gcc

git:
  submodules: false

notifications:
  irc:
    channels:
      - "irc.freenode.net#nupic-hackers"
  webhooks: http://issues.numenta.org:8081/travis

before_install:

  # Get Darwin64 libs for OSX
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then git clone https://github.com/numenta/nupic-darwin64.git; fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then (cd nupic-darwin64 && git reset --hard 6496136d3748f5f15eaf8e85e48c113d7447149b); fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then source nupic-darwin64/bin/activate; fi"
  # Install cmake on OSX
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install cmake; fi"
  # Install MySQL on OSX
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install mysql; fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then mysql.server start; fi"
  # Prefix env with our user installation
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then export PYTHONPATH=$PYTHONPATH:/Users/travis/Library/Python/$PY_VER/lib/python/site-packages; fi"

  # Necessary Linux prep work
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo add-apt-repository -y ppa:fkrull/deadsnakes; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get update; fi"
  # Install virtualenv
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install python$PY_VER python$PY_VER-dev python-virtualenv; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo ls -laFh /usr/lib/libpython$PY_VER.so; fi"
  # Execute virtualenv
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then virtualenv --python=`which python$PY_VER` .; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then source bin/activate; fi"
  # Workaround for multiprocessing.Queue SemLock error from run_opf_bechmarks_test.
  # See: https://github.com/travis-ci/travis-cookbooks/issues/155
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm; fi"
  # Install NuPIC python dependencies
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then travis_retry pip install -q -r $NUPIC/external/common/requirements.txt; fi"
  # Prefix env with our user installation
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then export PYTHONPATH=$PYTHONPATH:/home/travis/.local/lib/python$PY_VER/site-packages; fi"

install:
  # Verify cmake version
  - "cmake --version"
  # Verify python version
  - "python --version"
  # Build NuPIC
  - "cd $NUPIC"
  - "python$PY_VER setup.py install --user"
  # Show nupic installation folder by trying import nupic, if works, it prints the absolute path of nupic.__file__, which the installation folder itself.
  - "python -c 'import sys;import os;import nupic;sys.stdout.write(os.path.abspath(os.path.join(nupic.__file__, \"../..\")))'"

script:
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - python $NUPIC/scripts/run_tests.py $NUPIC/tests/unit/py2/nupic/algorithms/anomaly_likelihood_jeff_test.py
