branches:
  except:
    - gh-pages

language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      env:
        - PY_VER=2.6
    - os: osx
      compiler: clang
      env:
        - PY_VER=2.6
    - os: linux
      compiler: gcc
      env:
        - PY_VER=2.6
    - os: osx
      compiler: gcc
      env:
        - PY_VER=2.6
    - os: linux
      compiler: clang
      env:
        - PY_VER=2.7
    - os: osx
      compiler: clang
      env:
        - PY_VER=2.7
    - os: linux
      compiler: gcc
      env:
        - PY_VER=2.7
    - os: osx
      compiler: gcc
      env:
        - PY_VER=2.7

git:
  submodules: false

env:
  global:
    - NUPIC=$TRAVIS_BUILD_DIR
    - NTA=$HOME/nta/eng
    - PATH=$TRAVIS_BUILD_DIR/python/bin:$PATH

notifications:
  irc:
    channels:
      - "irc.freenode.net#nupic-hackers"
  webhooks: http://issues.numenta.org:8081/travis

before_install:
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo add-apt-repository -y ppa:fkrull/deadsnakes; fi
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install python$PY_VER python$PY_VER-dev python-virtualenv; fi
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install python$PY_VER; fi
  - sudo ls -laFh /usr/lib/libpython$PY_VER.so
  # Prefix env with our own python installation
  - "export PYTHONPATH=$PYTHONPATH:$NTA/lib/python$PY_VER/site-packages"
  - virtualenv --python=`which python$PY_VER` .
  - source bin/activate
  # Workaround for multiprocessing.Queue SemLock error from run_opf_bechmarks_test.
  # See: https://github.com/travis-ci/travis-cookbooks/issues/155
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  # Install NuPIC python dependencies
  - pip install -q -r $NUPIC/external/common/requirements.txt

install:
  - "mkdir -p $TRAVIS_BUILD_DIR/build/scripts"
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - "cmake --version"
  # Build NuPIC
  - "PYTHON=`which python$PY_VER` cmake $NUPIC -DPYTHON_LIBRARY=/usr/lib/libpython$PY_VER.so -DPROJECT_BUILD_RELEASE_DIR:STRING=$NTA"
  - "make -j3"
  - "cd"

script:
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  # legacy binary tests
  - "make tests_pyhtm"
  # actual unit tests
  - "make tests_run_all"
  - "cd"

  # run all example files
    # examples/bindings
  - "python$PY_VER $NUPIC/examples/bindings/sparse_matrix_how_to.py"
##  - "python $NUPIC/examples/bindings/svm_how_to.py" # tkinter missing in Travis build machine
##  - "python $NUPIC/examples/bindings/temporal_pooler_how_to.py" # tkinter too
    # examples/opf (run atleast 1 from each category)
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/anomaly/spatial/2field_few_skewed/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/anomaly/temporal/saw_200/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/classification/category_TP_1/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/missing_record/simple_0/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/multistep/hotgym/"
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/opfrunexperiment_test/simpleOPF/hotgym_1hr_agg/"
            # opf/experiments/params - skip now
  - "python$PY_VER $NUPIC/examples/opf/bin/OpfRunExperiment.py $NUPIC/examples/opf/experiments/spatial_classification/category_1/"
    # examples/prediction
  - "python$PY_VER $NUPIC/examples/prediction/RunExperiment.py $NUPIC/examples/prediction/experiments/dutyCycle/problem/"
    # examples/tp
  - "python$PY_VER $NUPIC/examples/tp/hello_tp.py"
  - "python$PY_VER $NUPIC/examples/tp/tp_test.py"

