branches:
  except:
    - gh-pages

language: cpp

os:
  - osx

compiler:
  - clang

env:
  global:
    - NUPIC=$TRAVIS_BUILD_DIR
    - PATH=$TRAVIS_BUILD_DIR/python/bin:$PATH

before_install:
  - ". ./ci/travis/before_install-osx.sh"

install:
  - ". ./ci/travis/install-osx.sh"

script:
  - . ./ci/travis/before_deploy.sh
