branches:
  except:
    - gh-pages

language: cpp

os:
  - linux

compiler:
  - clang

env:
  global:
    - NUPIC=$TRAVIS_BUILD_DIR
    - NTA=$HOME/nta/eng
    - PATH=$TRAVIS_BUILD_DIR/python/bin:$PATH
  matrix:
    - PY_VER=2.7

script:
  - git rev-parse --abbrev-ref HEAD

after_success:
  - sudo pip install coveralls
  - coveralls
